filter:
    excluded_paths:
        - 'vendor/*'
build:
    dependencies:
        override:
            - 'composer install --dev --no-interaction'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'


tools:
    php_mess_detector:
        filter:
            excluded_paths: ['vendor/*']
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            excluded_paths: ['vendor/*']
    php_code_coverage:
        test_command: vendor/bin/phpunit
        filter:
            excluded_paths: ['vendor/*']
    php_cpd:
        filter:
            excluded_paths: ['vendor/*']
    php_pdepend:
        excluded_dirs:
            1: vendor
    php_loc:
        excluded_dirs:
            - vendor